FROM docker.io/library/postgres:16-alpine

LABEL maintainer="Journii" \
      version="1.0.0" \
      description="PostgreSQL 16 con schema IDOSGD preinstalado"

ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres \
    POSTGRES_DB=IDOSGD_GOREL

COPY IDOSGD_PCM_POSTGRESQL_v3.6.sql /docker-entrypoint-initdb.d/01-schema.sql

VOLUME ["/var/lib/postgresql/data"]

EXPOSE 5432

CMD ["postgres"]