FROM docker.io/library/eclipse-temurin:8-jdk-jammy

ARG PAYARA_DIR=${PAYARA_DIR}
ARG TIMEZONE=${TIMEZONE}

RUN apt-get update && \
    apt-get install -y unzip && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /tmp /glassfish/tmp /glassfish/tmppcm /opt 

COPY payara5.zip /tmp/payara5.zip

RUN unzip /tmp/payara5.zip -d /opt && \
    rm /tmp/payara5.zip

CMD ["/opt/payara5/bin/asadmin", "start-domain", "--verbose", "domain1"]
