FROM docker.io/library/eclipse-temurin:8-jdk-jammy as base 

ARG TIMEZONE=${TIMEZONE}
ARG PAYARA_DIR=${PAYARA_DIR}

RUN apt-get update && \
    apt-get install -y unzip && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /tmp /glassfish/tmp /glassfish/tmppcm /opt 

COPY payara-5.2022.5.zip /tmp/payara5.zip
RUN unzip /tmp/payara5.zip -d /opt/payara5 && \
    rm /tmp/payara5.zip && \
    mv /tmp/payara-5.2022.5/payara5 /opt/payara5 && \
    rm -rf /tmp/payara-5.2022.5

CMD ["opt/payara5/bin/asadmin", "start-domain", "--verbose", "domain1"]
